### ISSUE TITLE
Cambio motore

### ISSUE THREAD

**Issue by mmaridev** [unibz-makerspace/osp-007-pills#5]
Dal team di sviluppo Arduino:
Sarebbe necessario modificare la struttura in modo da ospitare un motore stepper 28BYJ-48

**Comment by j54n1n** [comment]
Cambiamo la struttura come nel disegno tecnico del motore. Vedi 28BYJ-48.zip .
Per far andare il motore ci vuole un circuito integrato come il ULN2003. Come vi siete messo? Avete già disponibile una scheda simile come quella nel link https://arduino-info.wikispaces.com/SmallSteppers ? Penso che potete usare le stesse librerie.

[28BYJ-48.zip](https://github.com/unibz-makerspace/osp-007-pills/files/238039/28BYJ-48.zip)
